name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag sandesh2026/abook:0.1
    - name: Pushing the image on DockerHub
      run: docker push sandesh2026/abook:0.1
      
